.shared_windows_runners:
    tags:
    - shared-windows
    - windows
    - windows-1809

stages:
    - test
    - deploy

release:
    extends:
        - .shared_windows_runners
    stage: deploy
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.zip
    script:
        - ./build.ps1 --configuration Release --buildnumber $CI_PIPELINE_IID

debug:
    extends:
        - .shared_windows_runners
    stage: test
    script:
        - dotnet --info
    coverage: /Line coverage[\s\S].+%/
    artifacts:
        paths:
        - output/coverage
        reports:
            junit:
                - './**/TestResults/TestResults.xml'