.shared_windows_runners:
    tags:
    - shared-windows
    - windows
    - windows-1809

stages:
    - test
    - build

release:
    extends:
        - .shared_windows_runners
    stage: build
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.zip
    script:
        - ./build.ps1 --configuration Release

debug:
    extends:
        - .shared_windows_runners
    stage: test
    script:
        - ./build.ps1
    coverage: /Line coverage[\s\S].+%/
    artifacts:
        paths:
        - output/coverage
        reports:
            junit:
                - './**/TestResults/TestResults.xml'